#!/bin/bash

# concept script that installs a service on Red Hat or Ubuntu

if grep -i 'ubuntu' /etc/os-release >/dev/null
then
	PACKAGE_MANAGER=apt
fi

if grep -i 'red hat' /etc/os-release >/dev/null
then
	PACKAGE_MANAGER=yum
fi

if [ -z $1 ]
then
	echo enter name of package you want to install
	read PACKAGE
else
	PACKAGE=$1
fi

#### debugging
echo PACKAGE_MANAGER=$PACKAGE_MANAGER
echo PACKAGE=$PACKAGE

sudo $PACKAGE_MANAGER install $PACKAGE -y
