#!/bin/bash

# due to the location in the course where this script is used it lacks the proper conditional checks
sudo apt install -y vsftpd lftp
sudo sed -i -e 's/anonymous_enable=NO/anonymous_enable=YES/' /etc/vsftpd.conf
sudo sed -i -e 's/listen=NO/listen=YES/' /etc/vsftpd.conf
sudo sed -i -e 's/listen_ipv6=YES/listen_ipv6=NO/' /etc/vsftpd.conf

# again this is not pretty but I don't want to show anything that hasn't been covered yet
sudo systemctl disable --now vsftpd
sudo systemctl enable --now vsftpd
sudo cp /etc/hosts /srv/ftp/

# fetching a file with a here document
lftp localhost <<ENDSESSION
ls
get hosts
ls
quit
ENDSESSION
